// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductUp product up
//
// swagger:model ProductUp
type ProductUp struct {

	// category name
	CategoryName string `json:"category_name,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// price
	Price int32 `json:"price,omitempty"`

	// sku
	Sku int64 `json:"sku,omitempty"`

	// unit stock
	UnitStock int32 `json:"unitStock,omitempty"`
}

// Validate validates this product up
func (m *ProductUp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this product up based on context it is used
func (m *ProductUp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductUp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductUp) UnmarshalBinary(b []byte) error {
	var res ProductUp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
