ServerConfig:
  AppVersion: 1.0.0
  Mode: Development
  RoutePrefix: /api/v1/trade-cart-api
  Debug: false
  Port: 8080
  TimeoutSecs: 60
  ReadTimeoutSecs: 60
  WriteTimeoutSecs: 12

JWTConfig:
  SessionTime: 3600
  SecretKey: MarioCantFindPrincess

DBConfig:
  DataSourceName: postgres://deneme:deneme@localhost:5432/trade_cart?sslmode=disable
  Name: trade-cart
  MaxOpen: 50
  MaxIdle: 50
  MaxLifetime: 5
  MigrationFolder: file://migrations

Logger:
  Development: true
  Encoding: json
  Level: info

